### ISSUE TITLE
调用SnsApi.JsCode2Json(_wxOpenAppId, _wxOpenAppSecret, code)出现下面错误是什么原因

### ISSUE THREAD

**Issue by newpost** [Senparc/Senparc.CO2NET#128]
at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Senparc.CO2NET.SenparcDI.GetIServiceProvider(Boolean useGlobalScope)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpGet(String url, Encoding encoding)
   at Senparc.CO2NET.HttpUtility.Get.GetJson[T](String url, Encoding encoding, Action`2 afterReturnText)
   at Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting)
   at Senparc.Weixin.WxOpen.AdvancedAPIs.Sns.SnsApi.JsCode2Json(String appId, String secret, String jsCode, String grantType, Int32 timeOut)

**Comment by JeffreySu** [comment]
只有跟踪信息，没开单你你具体的错误信息是什么？

**Comment by git119** [comment]
No service for type 'Senparc.CO2NET.HttpUtility.SenparcHttpClient' has been registered.

**Comment by git119** [comment]
我遇到这个方法报错，内容如下
No service for type 'Senparc.CO2NET.HttpUtility.SenparcHttpClient' has been registered.

**Comment by JeffreySu** [comment]
是不是没有按照Demo的说明进行注册？

Thanks
苏震巍 Jeffrey Su

________________________________
