### ISSUE TITLE
dotnet core 2.2 调用Senparc.CO2NET的方法报错

### ISSUE THREAD

**Issue by webtom-hzm** [Senparc/Senparc.CO2NET#159]
dotnet core 2.2 调用Senparc.CO2NET的方法报错，请问是什么原因？
System.ArgumentNullException: Value cannot be null.
Parameter name: services
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Senparc.CO2NET.SenparcDI.GetIServiceProvider(Boolean useGlobalScope)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpGet(String url, Encoding encoding)
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.GetToken(String appid, String secret, String grant_type)

**Comment by JeffreySu** [comment]
@webtom-hzm  需要提供 IServiceCollection services 这个参数，不能为 null。如果是 .NET Framework 可以为 null。
