### ISSUE TITLE
项目启动抛异常：The type initializer for 'Nested' threw an exception

### ISSUE THREAD

**Issue by luoxgwb** [Senparc/Senparc.CO2NET#288]
已经注册 services.AddMemoryCache();

启动还是报错：Senparc.CO2NET.Exceptions.CacheException: IMemoryCache 依赖注入未设置！如果您使用的是本地缓存，请确保在 Startup.cs 中执行了 services.AddMemoryCache() 方法！

System.TypeInitializationException: The type initializer for 'Nested' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Nested' threw an exception.
 ---> Senparc.CO2NET.Exceptions.CacheException: IMemoryCache 依赖注入未设置！如果您使用的是本地缓存，请确保在 Startup.cs 中执行了 services.AddMemoryCache() 方法！
   at Senparc.CO2NET.Cache.LocalObjectCacheHelper.get_LocalObjectCache()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy..ctor()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.Nested..cctor()

**Comment by luoxgwb** [comment]
经过长时间排查，日志组件从NLog切换到Serilog，在CreateHostBuilder方法中只要添加了UseSerilog，你们这个[Senparc.CO2NET]就会抛异常，我服了呀

**Comment by luoxgwb** [comment]
只要没有添加UseSerilog方法，就算没有注册IMemoryCache()，也不会抛异常，注册了UseSerilog，不管怎么都会抛异常，我一直使用Redis缓存

**Comment by JeffreySu** [comment]
@luoxgwb 可以发一下所有启动过程的代码，帮您排查一下，框架本身并没有对 Log 库做其他特殊处理。

**Comment by JeffreySu** [comment]
> @luoxgwb 可以发一下所有启动过程的代码，帮您排查一下，框架本身并没有对 Log 库做其他特殊处理。

@luoxgwb 请问问题仍然存在吗？需要你能提供重现的代码才比较好判断。目前框架本身没有做限制。

**Comment by publicuserCY** [comment]
我也遇到了这个问题，.net8，启动代码如下：
var builder = WebApplication.CreateBuilder(args);
//Cache
builder.Services.AddMemoryCache();
//微信小程序
builder.Services.AddSenparcWeixin(builder.Configuration);
//Serilog
builder.Logging.ClearProviders();
//builder.Host.UseSerilog();  //注释掉下面带参数的方法，换这行就没问题
builder.Host.UseSerilog((context, loggerConfiguration) =>
{
    loggerConfiguration.ReadFrom.Configuration(context.Configuration);
});

var app = builder.Build();
app.UseDefaultFiles();
app.UseStaticFiles();
app.UseRouting();
app.UseRateLimiter();
app.UseAuthorization();
app.MapControllers().RequireAuthorization();
//启用微信配置（必须）
var registerService = app.UseSenparcWeixin(
        env: app.Environment,
        senparcSetting: null /* 不为 null 则覆盖 appsettings  中的 SenpacSetting 配置*/,
        senparcWeixinSetting: null /* 不为 null 则覆盖 appsettings  中的 SenpacWeixinSetting 配置*/,
        globalRegisterConfigure: register => { /* CO2NET 全局配置 */ },
        weixinRegisterConfigure: (register, weixinSetting) =>
        {
            /* 注册公众号或其他平台信息（可以执行多次，注册多个公众号）*/
            register.RegisterWxOpenAccount(weixinSetting, "小程序");
        }
 );
app.Run();

**Comment by publicuserCY** [comment]
原因找到了，最开始有一段用于启动时使用日志的代码
删除：
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateBootstrapLogger();
改成：
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateLogger();
