### ISSUE TITLE
项目升级到.net core 2.2后初始化错误

### ISSUE THREAD

**Issue by LGinC** [Senparc/Senparc.CO2NET#49]
Application startup exception: System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: services
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Senparc.CO2NET.SenparcDI.GetIServiceProvider()
   at Senparc.CO2NET.Cache.LocalObjectCacheHelper.get_LocalObjectCache()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy..ctor()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.Nested..cctor()
   --- End of inner exception stack trace ---
   at Senparc.Weixin.Cache.LocalContainerCacheStrategy.<>c.<.ctor>b__2_0()
   at Senparc.CO2NET.Cache.CacheStrategyDomainWarehouse.RegisterCacheStrategyDomain(IDomainExtensionCacheStrategy domainCacheStrategy)
   at Senparc.Weixin.Cache.LocalContainerCacheStrategy.Nested..cctor()
   --- End of inner exception stack trace ---
   at Senparc.Weixin.WeixinRegister.UseSenparcWeixin(IRegisterService registerService, SenparcWeixinSetting senparcWeixinSetting, SenparcSetting senparcSetting)
   at Tensee.Banch.BanchApplicationModule.Initialize() in D:\workspace\C#\DuoMai_TooHot\src\Tensee.Banch.Application\BanchApplicationModule.cs:line 50
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Abp.Modules.AbpModuleManager.StartModules() in D:\Github\aspnetboilerplate\src\Abp\Modules\AbpModuleManager.cs:line 48
   at Abp.AbpBootstrapper.Initialize() in D:\Github\aspnetboilerplate\src\Abp\AbpBootstrapper.cs:line 155
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.InitializeAbp(IApplicationBuilder app) in D:\Github\aspnetboilerplate\src\Abp.AspNetCore\AspNetCore\AbpApplicationBuilderExtensions.cs:line 67
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app, Action`1 optionsAction) in D:\Github\aspnetboilerplate\src\Abp.AspNetCore\AspNetCore\AbpApplicationBuilderExtensions.cs:line 38
   at Tensee.Banch.Web.Startup.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in D:\workspace\C#\DuoMai_TooHot\src\Tensee.Banch.Web.Host\Startup\Startup.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/49796224-1597b700-fd77-11e8-9b9d-b3468acb938e.png)
![image](https://user-images.githubusercontent.com/15363011/49796258-2b0ce100-fd77-11e8-8898-0923756cd782.png)

已配置，这句注册就是上边报错的
at Tensee.Banch.BanchApplicationModule.Initialize() in D:\workspace\C#\DuoMai_TooHot\src\Tensee.Banch.Application\BanchApplicationModule.cs:line 50

**Comment by JeffreySu** [comment]
对的，如果是自己编译DLL要根据自己的版本做一些判断，这些标记只是给我们这里生成的时候用的。
